lkroesen/BubbleBobble

src/main/java/website/frontrow/board/Bubble.java, src/main/java/website/frontrow/board/Enemy.java, src/main/java/website/frontrow/board/Mover.java, src/main/java/website/frontrow/board/Player.java, src/main/java/website/frontrow/board/Unit.java, src/main/java/website/frontrow/level/Cell.java, src/main/java/website/frontrow/sprite/SpriteStore.java, src/main/java/website/frontrow/util/AABB.java, src/main/java/website/frontrow/util/CollisionHandler.java, src/main/java/website/frontrow/util/Range.java, src/test/java/website/frontrow/board/BubbleTest.java, src/test/java/website/frontrow/board/EnemyTest.java, src/test/java/website/frontrow/board/MoverTest.java, src/test/java/website/frontrow/board/PlayerTest.java, src/test/java/website/frontrow/board/UnitTest.java, src/test/java/website/frontrow/level/CellTest.java, src/test/java/website/frontrow/sprite/SpriteStoreTest.java, src/test/java/website/frontrow/util/AABBTest.java, src/test/java/website/frontrow/util/RangeTest.java
I moved all the movement logic from Unit to Mover to clean up Unit. 
I also removed the unnecessary faceLeft variable in Unit. It was redundant because the direction was stored in the variable direction anyway.
Please look the changes over carefully before merging them, but don't take too long. The changes are pretty extreme, so branches which are far behind will have problems when they're going to be merged.
=> Refactor: Move movement logic from Unit to Mover

src/main/java/website/frontrow/Launcher.java, src/main/java/website/frontrow/board/Mover.java, src/main/java/website/frontrow/game/Game.java, src/main/java/website/frontrow/game/GameConstants.java, src/main/java/website/frontrow/ui/ButtonPanel.java, src/main/java/website/frontrow/ui/JBubbleBobbleUI.java, src/main/java/website/frontrow/ui/JBubbleKeyListener.java, src/test/java/website/frontrow/ui/JBubbleKeyListenerTest.java
I fixed that actions which belonged to keys were not being performed.
Please check my work and then merge it.
=> Fix keystrokes not resulting in actions.

src/main/java/website/frontrow/Launcher.java, src/main/java/website/frontrow/board/Mover.java, src/main/java/website/frontrow/board/Unit.java, src/main/java/website/frontrow/level/Cell.java, src/main/java/website/frontrow/level/Level.java, src/main/java/website/frontrow/util/Collision.java, src/main/java/website/frontrow/util/CollisionHandler.java, src/main/java/website/frontrow/util/Point.java, src/test/java/website/frontrow/board/MoverTest.java, src/test/java/website/frontrow/level/CellTest.java, src/test/java/website/frontrow/util/CollisionHandlerTest.java, src/test/java/website/frontrow/util/PointTest.java
I revised collisions to be cleaner (and allow certain, currently impossible things)
=> Revise Collisions

src/main/java/website/frontrow/Launcher.java, src/main/java/website/frontrow/board/Bubble.java, src/main/java/website/frontrow/board/Enemy.java, src/main/java/website/frontrow/board/Mover.java, src/main/java/website/frontrow/board/Player.java, src/main/java/website/frontrow/game/Game.java, src/main/java/website/frontrow/level/Level.java, src/main/java/website/frontrow/level/MapParser.java, src/main/java/website/frontrow/logger/DumpLog.java, src/main/java/website/frontrow/logger/Log.java, src/main/java/website/frontrow/logger/Logable.java, src/main/java/website/frontrow/sprite/ImageStore.java, src/main/java/website/frontrow/sprite/SpriteStore.java, src/main/java/website/frontrow/ui/ButtonPanel.java, src/main/java/website/frontrow/ui/JBubbleBobbleUI.java, src/main/java/website/frontrow/ui/PlayingFieldPanel.java, src/main/java/website/frontrow/ui/ScorePanel.java, src/main/java/website/frontrow/ui/SidePanel.java, src/main/java/website/frontrow/util/CollisionHandler.java, src/main/java/website/frontrow/util/MusicPlayer.java, src/main/java/website/frontrow/util/MusicThread.java, src/test/java/website/frontrow/logger/DumpLogTest.java, src/test/java/website/frontrow/logger/LogTest.java
Enable logging of actions taken in the game.
F1 writes a file of all actions to temporary files.
=> Add logging into the game.

src/main/java/website/frontrow/board/Mover.java, src/main/java/website/frontrow/game/GameConstants.java, src/main/java/website/frontrow/ui/JBubbleKeyListener.java, src/test/java/website/frontrow/board/MoverTest.java
Changed some constants and prevented jump & bubble spamming.
<performance, bug
=> tweaked movement stats.

src/main/java/website/frontrow/ui/JBubbleKeyListener.java
I was unable to reproduce the exception after the change.
However, due to the nature of this exception I may just have been unlucky.
<bug
=> Fix the ConcurrentModificationException in the KeyListener

src/main/java/website/frontrow/level/Cell.java, src/main/java/website/frontrow/util/CollisionHandler.java, src/test/java/website/frontrow/util/CollisionHandlerTest.java
Make collisions more reliable for platforms, and increase precision.
>bug
=> Tweak Collisions

src/main/java/website/frontrow/util/CollisionHandler.java
=> Fix the bubble not disappearing

src/main/java/website/frontrow/board/Mover.java, src/main/java/website/frontrow/level/Level.java, src/main/java/website/frontrow/level/MapParser.java, src/main/java/website/frontrow/util/CollisionHandler.java, src/main/resources/level/3.txt, src/test/java/website/frontrow/board/MoverTest.java, src/test/java/website/frontrow/level/LevelTest.java, src/test/java/website/frontrow/util/CollisionHandlerTest.java, src/test/resources/testMove.txt
Reverts lkroesen/BubbleBobble#37
So... I kinda didn't see it would merge into master...
=> Revert "Add mover warping to level."

src/main/java/website/frontrow/artificial/intelligence/ArtificialIntelligence.java, src/main/java/website/frontrow/board/Enemy.java, src/main/java/website/frontrow/level/Cell.java, src/main/java/website/frontrow/util/CollisionHandler.java, src/main/resources/level/003.txt, src/main/resources/level/005.txt, src/main/resources/level/008.txt, src/test/java/website/frontrow/util/CollisionHandlerTest.java
Additionally tweaked some of the levels to improve ai performance.
Changed the Collision handler a little bit to properly indicate wall collisions.
<performance, feature
=> Improved wall collisions for ai.

src/main/java/website/frontrow/board/Player.java
Warning, this is a quick hotfix and a bodge.
< bug
=> Fix lives below 0 detection.

src/main/java/website/frontrow/Launcher.java, src/main/java/website/frontrow/game/Game.java, src/main/resources/game_won.txt
=> Actually add winning the level

src/main/java/website/frontrow/board/Bubble.java, src/main/java/website/frontrow/board/Mover.java, src/main/java/website/frontrow/board/behaviour/BubbleGravityBehaviour.java, src/main/java/website/frontrow/board/behaviour/DefaultGravityBehaviour.java, src/main/java/website/frontrow/board/behaviour/GravityBehaviour.java, src/test/java/website/frontrow/board/behaviour/BubbleGravityBehaviourTest.java, src/test/java/website/frontrow/board/behaviour/DefaultGravityBehaviourTest.java
This branch contains a new layout to apply gravity to movers using the fancy behaviour design pattern.
< organisation
=> Add gravity behaviour design pattern.

src/main/java/website/frontrow/board/Bubble.java, src/main/java/website/frontrow/board/Enemy.java, src/main/java/website/frontrow/board/Player.java, src/main/java/website/frontrow/board/Unit.java, src/main/java/website/frontrow/ui/status/PlayerStatusPanel.java, src/main/java/website/frontrow/ui/status/StatusPanel.java
=> Remove map, simplify.

src/main/java/website/frontrow/game/Game.java, src/main/java/website/frontrow/level/Level.java
Wrap the spawning spot around, so the next player spawns in a different spot.
< feature
=> Use multiple spawning positions.

src/main/java/website/frontrow/Launcher.java, src/main/java/website/frontrow/artificial/intelligence/ArtificialIntelligence.java, src/main/java/website/frontrow/logger/DumpLog.java, src/main/java/website/frontrow/logger/Log.java, src/test/java/website/frontrow/logger/DumpLogTest.java, src/test/java/website/frontrow/logger/LogTest.java
=> Make Logger classes Singleton

src/main/java/website/frontrow/board/Mover.java, src/main/java/website/frontrow/board/Player.java, src/main/java/website/frontrow/level/Level.java, src/test/java/website/frontrow/LauncherTest.java, src/test/java/website/frontrow/artificial/intelligence/ArtificialIntelligenceTest.java, src/test/java/website/frontrow/board/BubbleTest.java, src/test/java/website/frontrow/board/EnemyTest.java, src/test/java/website/frontrow/board/MoverTest.java, src/test/java/website/frontrow/board/PlayerTest.java, src/test/java/website/frontrow/board/UnitTest.java, src/test/java/website/frontrow/game/GameTest.java, src/test/java/website/frontrow/level/CellTest.java, src/test/java/website/frontrow/level/LevelTest.java, src/test/java/website/frontrow/level/MapParserTest.java, src/test/java/website/frontrow/sprite/EmptySpriteTest.java, src/test/java/website/frontrow/sprite/ImageStoreTest.java, src/test/java/website/frontrow/sprite/JBubbleBobbleSpritesTest.java, src/test/java/website/frontrow/sprite/SpriteStoreTest.java, src/test/java/website/frontrow/ui/JBubbleBobbleUITest.java, src/test/java/website/frontrow/ui/JBubbleKeyListenerTest.java, src/test/java/website/frontrow/ui/status/StatusLabelPanelTest.java, src/test/java/website/frontrow/util/AABBTest.java, src/test/java/website/frontrow/util/CollisionComputerTest.java, src/test/java/website/frontrow/util/GridTest.java, src/test/java/website/frontrow/util/PointTest.java, src/test/java/website/frontrow/util/RangeTest.java
=> Update tests with some new tests and remove all abbreviations

src/main/java/website/frontrow/ui/ModeMenu.java, src/main/java/website/frontrow/util/FileNameCollector.java, src/test/java/website/frontrow/util/FileNameCollectorTest.java
=> Make FileNameCollector Singleton.

src/main/java/website/frontrow/board/Mover.java, src/main/java/website/frontrow/board/Player.java, src/main/java/website/frontrow/board/Unit.java, src/main/java/website/frontrow/game/Game.java, src/main/java/website/frontrow/ui/status/SidePanel.java, src/test/java/website/frontrow/GameTest.java
Allow restarting of the current game by a press of a button.
< feature
=> Add restart button

src/main/java/website/frontrow/artificial/intelligence/ArtificialIntelligence.java, src/main/java/website/frontrow/board/Enemy.java, src/test/java/website/frontrow/artificial/intelligence/ArtificialIntelligenceTest.java, src/test/java/website/frontrow/board/EnemyTest.java
The AI now responds to the second player, when player one has died (in the game ;) ).
=> Dev fix ai multiplayer

src/main/java/website/frontrow/game/Game.java, src/test/java/website/frontrow/game/GameTest.java
A life is added by nextLevel() when a player clears a level with 1 or 2 lives.
=> Dev level transition add life

src/main/java/website/frontrow/level/Level.java
Fixes a ConcurrentModificationException.
< bug
=> Fix concurrency issues
